# Travis CI config - https://docs.travis-ci.com/user/languages/java/
language: java

# Improve build speed - https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# Customizing the build - https://docs.travis-ci.com/user/customizing-the-build/
install:
- if [ "$DESC" = "openjdk10 - H2" ] || [ "$DESC" = "openjdk10 - Pitest - H2" ];
  then mvn install -P h2-database -D skipTests=true -D maven.javadoc.skip=true -B -V;
  fi
- if [ "$DESC" = "openjdk10 - MySQL" ] || [ "$DESC" = "openjdk10 - Pitest - MySQL" ];
  then mvn install -P mysql-database -D skipTests=true -D maven.javadoc.skip=true -B -V;
  fi
- if [ "$DESC" = "openjdk10 - Oracle" ] || [ "$DESC" = "openjdk10 - Pitest - Oracle" ];
  then mvn install -P oracle-database -D skipTests=true -D maven.javadoc.skip=true -B -V;
  fi
- if [ "$DESC" = "openjdk10 - PostgreSQL" ] || [ "$DESC" = "openjdk10 - Pitest - PostgreSQL" ];
  then mvn install -P postgresql-database -D skipTests=true -D maven.javadoc.skip=true -B -V;
  fi

script:
- if [ "$DESC" = "openjdk10 - H2" ];
  then mvn test -P h2-database -B;
  fi
- if [ "$DESC" = "openjdk10 - Pitest - H2" ];
  then mvn test -P activate-pitest -P h2-database -B;
  fi
- if [ "$DESC" = "openjdk10 - MySQL" ];
  then mvn test -P mysql-database -B;
  fi
- if [ "$DESC" = "openjdk10 - Pitest - MySQL" ];
  then mvn test -P activate-pitest -P mysql-database -B;
  fi
- if [ "$DESC" = "openjdk10 - Oracle" ];
  then mvn test -P oracle-database -B;
  fi
- if [ "$DESC" = "openjdk10 - Pitest - Oracle" ];
  then mvn test -P activate-pitest -P oracle-database -B;
  fi
- if [ "$DESC" = "openjdk10 - PostgreSQL" ];
  then mvn test -P postgresql-database -B;
  fi
- if [ "$DESC" = "openjdk10 - Pitest - PostgreSQL" ];
  then mvn test -P activate-pitest -P postgresql-database -B;
  fi

# Matrix expansion - https://docs.travis-ci.com/user/build-stages/matrix-expansion/
matrix:
  fast_finish: true
  include:
  - jkd: openjdk10
    end: DESC="openjdk10 - H2"
  - jdk: openjdk10
    env: DESC="openjdk10 - Pitest - H2"
  - jdk: openjdk10
    env: DESC="openjdk10 - MySQL"
  - jdk: openjdk10
    env: DESC="openjdk10 - Pitest - MySQL"
  - jdk: openjdk10
    env: DESC="openjdk10 - Oracle"
  - jdk: openjdk10
    env: DESC="openjdk10 - Pitest - Oracle"
  - jdk: openjdk10
    env: DESC="openjdk10 - PostgreSQL"
  - jdk: openjdk10
    env: DESC="openjdk10 - Pitest - PostgreSQL"

# Codecov - https://github.com/codecov/example-java
after_success:
- bash <(curl -s https://codecov.io/bash)

# Notifications - https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
    - qThegamEp@gmail.com
    on_success: always
    on_failure: always
