DROP TABLE IF EXISTS PUBLIC.BOOKS;

CREATE TABLE PUBLIC.BOOKS (
  ID         SERIAL       NOT NULL,
  NAME       VARCHAR(255) NOT NULL,
  AUTHOR     VARCHAR(255) NOT NULL,
  PRINT_YEAR INTEGER      NOT NULL,
  IS_READ    BOOLEAN      NOT NULL DEFAULT FALSE,
  CONSTRAINT BOOKS_PRIMARY_KEY PRIMARY KEY (ID)
)
