DROP TABLE IF EXISTS PUBLIC.BOOK;

CREATE TABLE PUBLIC.BOOK (
  ID         INTEGER      NOT NULL AUTO_INCREMENT,
  NAME       VARCHAR(255) NOT NULL,
  AUTHOR     VARCHAR(255) NOT NULL,
  PRINT_YEAR INTEGER(4)   NOT NULL,
  IS_READ    BOOLEAN      NOT NULL DEFAULT FALSE,
  CONSTRAINT BOOK_PRIMARY_KEY PRIMARY KEY (ID)
)
