BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.BOOK';
  EXCEPTION
  WHEN OTHERS
  THEN
    IF SQLCODE != -942
    THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE SYSTEM.BOOK (
  ID         NUMBER(*)              NOT NULL,
  NAME       VARCHAR(255)           NOT NULL,
  AUTHOR     VARCHAR(255)           NOT NULL,
  PRINT_YEAR NUMBER(4)              NOT NULL,
  IS_READ    NUMBER(1, 0) DEFAULT 0 NOT NULL,
  CONSTRAINT BOOK_PRIMARY_KEY PRIMARY KEY (ID)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE BOOK_ID_SEQUENCE';
  EXCEPTION
  WHEN OTHERS
  THEN
    IF SQLCODE != -2289
    THEN
      RAISE;
    END IF;
END;
/

CREATE SEQUENCE BOOK_ID_SEQUENCE;

CREATE OR REPLACE TRIGGER BOOK_ID_TRIGGER
  BEFORE INSERT
  ON SYSTEM.BOOK
  FOR EACH ROW
  WHEN (NEW.ID IS NULL)
  BEGIN
    SELECT BOOK_ID_SEQUENCE.NEXTVAL
        INTO :NEW.ID FROM DUAL;
  END;
/
