package com.qthegamep.bookmanager3.entity;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;

/**
 * This class is an entity.
 * There is an no args constructor, getters and setters for all fields, override equals, hashCode and toString methods
 * generated by lombok.
 * Id that is generated by database is excluded from hashCode and equals methods. See links.
 *
 * @see <a href="https://vladmihalcea.com/the-best-way-to-implement-equals-hashcode-and-tostring-with-jpa-and-hibernate/">
 * The best way to implement equals, hashCode and toString with JPA and Hibernate</a>
 */
@Data
@Entity
@DynamicInsert
@DynamicUpdate
@Table(name = "BOOK")
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false)
    @EqualsAndHashCode.Exclude
    private Long id;

    @Column(name = "NAME", nullable = false)
    private String name;

    @Column(name = "AUTHOR", nullable = false)
    private String author;

    @Column(name = "PRINT_YEAR", nullable = false)
    private int printYear;

    @Column(name = "IS_READ", nullable = false)
    private boolean read;
}
